# Generated by Django 5.1.5 on 2025-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='postUrl',
            field=models.CharField(default='https://www.instagram.com/abujacar/', max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('Gmc', 'GMC'), ('Honda', 'Honda'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('Mclaren', 'McLaren'), ('Mercedes Benz', 'Mercedes Benz'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Rolls Royce', 'Rolls Royce'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], default='lexus', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Grey'), ('orange', 'Orange'), ('Brown', 'Brown')], default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='RX 350', max_length=9),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
