# Generated by Django 5.1.5 on 2025-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_about_delete_featurepost_delete_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('Gmc', 'GMC'), ('Honda', 'Honda'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('Mclaren', 'McLaren'), ('Mercedes Benz', 'Mercedes Benz'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Rolls Royce', 'Rolls Royce'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Grey'), ('orange', 'Orange'), ('Brown', 'Brown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('USED', 'Used'), ('FOREIGN_USED', 'Foreign Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='postUrl',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='variant',
            field=models.CharField(default='Luxury', help_text="Enter all related separated by a space. E.g., 'Standard Luxury Sports Electric Hybrid Diesel'", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
