# Generated by Django 5.1.5 on 2025-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_car_amount_alter_car_brand_alter_car_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='variant',
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used'), ('Foreign Used', 'Foreign Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='postUrl',
            field=models.URLField(),
        ),
    ]
